- name: auth_doc
  copy:
    src: authdoc.json
    dest: /tmp/authdoc.json
    decrypt: yes
    mode: '0400'
- name: copy customer config
  copy:
    src: customer_config.yaml
    dest: /tmp/customer_config.yaml
    mode: '0400'
- name: Create Customer 
  sample_customer:
    auth_doc: /tmp/authdoc.json
    name: '{{ customer_name }}'
    customer_config: /tmp/customer_config.yaml
  register: customer
- name: debug
  debug:
    var: customer
- name: delete auth doc
  file:
    state: absent
    path: /tmp/authdoc.json
- name: delete customer config
  file:
    state: absent
    path: /tmp/customer_config.yaml
