- name: auth_doc
  copy:
    src: authdoc.json
    dest: /tmp/authdoc.json
    decrypt: yes
    mode: '0400'
- name: install agilicus sdk
  ansible.builtin.pip:
    name:
      - agilicus
    extra_args: --upgrade
- name: Create Customer 
  sample_customer:
    auth_doc: /tmp/authdoc.json
    name: '{{ customer_name }}'
    admin_users: '{{ admin_users | default | to_json }}'
  register: customer
- name: debug
  debug:
    var: customer
- name: delete auth doc
  file:
    state: absent
    path: /tmp/authdoc.json
