- name: auth_doc
  copy:
    src: authdoc.json
    dest: /tmp/authdoc.json
    decrypt: yes
    mode: '0400'
  delegate_to: "{{ agilicus_sdk }}"
- name: create forwarder 
  add_forwarder:
    auth_doc: /tmp/authdoc.json
    customer: "{{ customer_name }}"
    to_connector: "{{ inventory_hostname }}"
    from_connectors: "{{ from_connectors | to_json }}"
    port_offset: "{{ port_offset | default(0) }}"
    forwarder_bind_address: "{{ bind_address }}"
  delegate_to: "{{ agilicus_sdk }}"
  register: connector
- name: debug
  debug:
    var: connector
- name: delete auth doc
  file:
    state: absent
    path: /tmp/authdoc.json
  delegate_to: "{{ agilicus_sdk }}"
