- name: auth_doc
  copy:
    src: authdoc.json
    dest: /tmp/authdoc.json
    decrypt: yes
    mode: '0400'
  delegate_to: 127.0.0.1
- name: create forwarder 
  add_connector:
    auth_doc: /tmp/authdoc.json
    customer: "{{ customer_name }}"
    connector_name: "{{ inventory_hostname }}"
    forwarding_connectors: "{{ forwarding_connectors | to_json }}"
    port_offset: "{{ port_offset | default(0) }}"
    forwarder_bind_address: "{{ bind_address }}"
  delegate_to: 127.0.0.1
  register: connector
- name: debug
  debug:
    var: connector
- name: delete auth doc
  file:
    state: absent
    path: /tmp/authdoc.json
  delegate_to: 127.0.0.1
