- hosts: localhost 
  vars:
    admin_users:
      - mike@agilicus.com
  roles:
    - customer
- hosts: connectors
  vars:
    networks:
      - name: test1
        hostname: localhost
        port: 80
  roles:
    - connector
- hosts: forwarders
  vars:
  roles:
    - connector
