- hosts: agilicus_sdk
  vars:
    admin_users:
      - mike@agilicus.com
  roles:
    - deps
    - customer
- name: build cloud connectors
  hosts: onprem
  vars:
    networks:
      - name: prometheus
        hostname: "{{ prometheus_host | default(inventory_hostname) }}"
        port: 9090
      - name: ignition
        hostname: "{{ ignition_host | default(inventory_hostname) }}"
        port: 8080
      - name: kafka
        hostname: "{{ kafka_host | default(inventory_hostname) }}"
        port: 9092
  roles:
    - connector
- name: build onprem connectors
  hosts: cloud
  vars:
    networks:
      - name: influx
        hostname: "{{ influx_host | default(inventory_hostname) }}"
        port: 8086
      - name: postgres
        hostname: "{{ postgres_host | default(inventory_hostname) }}"
        port: 5432
  roles:
    - connector
- name: setup forwarding from cloud -> onprem
  hosts: onprem
  vars:
    from_connectors: "{{ groups['cloud'] }}"
    bind_address: "{{ forwarder_bind_address | default('0.0.0.0') }}"
    port_offset: "{{ forwarder_port_offset | default(10000) }}"
  roles:
    - forwarder
- name: setup forwarding from onprem -> cloud
  hosts: cloud
  vars:
    from_connectors: "{{ groups['onprem'] }}"
    bind_address: "{{ forwarder_bind_address | default('0.0.0.0') }}"
    port_offset: "{{ forwarder_port_offset | default(10000) }}"
  roles:
    - forwarder
- name: install connectors
  hosts: onprem, cloud
  roles:
    - install_connector
