- hosts: localhost 
  vars:
    admin_users:
      - mike@agilicus.com
  roles:
    - deps
    - customer
- hosts: connectors
  vars:
    networks:
      - name: test1
        hostname: localhost
        port: 80
  roles:
    - connector
    - install_connector
- hosts: forwarders
  roles:
    - forwarder
    - install_connector
