- name: auth_doc
  copy:
    src: authdoc.json
    dest: /tmp/authdoc.json
    decrypt: yes
    mode: '0400'
  delegate_to: 127.0.0.1
- name: install agilicus sdk
  ansible.builtin.pip:
    name:
      - agilicus
    extra_args: --upgrade
  delegate_to: 127.0.0.1
- name: create connector
  add_connector:
    auth_doc: /tmp/authdoc.json
    customer: "{{ customer_name }}"
    connector_name: "{{ inventory_hostname }}"
    networks: "{{ networks | default() | to_json }}"
    forwarding_connectors: "{{ forwarding_connectors | default() | to_json }}"
    port_offset: "{{ port_offset | default(0) }}"
    forwarder_bind_address: "{{ bind_address | default() }}"
  delegate_to: 127.0.0.1
  register: connector
- name: debug
  debug:
    var: connector
- name: create connector authentication document
  connector_auth_doc:
    auth_doc: /tmp/authdoc.json
    customer: "{{ customer_name }}"
    connector_name: "{{ inventory_hostname }}"
  delegate_to: 127.0.0.1
  register: auth_doc
- name: copy authdoc to remote
  copy:
    content: "{{ auth_doc }}"
    dest: /tmp/connector_auth_doc.json
    mode: '0400'
- name: fetch agilicus
  ansible.builtin.get_url:
    url: https://agilicus.com/www/releases/secure-agent/latest/agilicus-agent
    mode: '0770'
    dest: /tmp
- name: install agilicus connector
  ansible.builtin.command:
    cmd: /tmp/agilicus-agent client --install --authentication-document /tmp/connector_auth_doc.json --agent-id "{{connector['metadata']['id']}}"
- name: delete auth doc
  file:
    state: absent
    path: /tmp/authdoc.json
