- name: auth_doc
  copy:
    src: authdoc.json
    dest: /tmp/authdoc.json
    decrypt: yes
    mode: '0400'
  delegate_to: "{{ agilicus_sdk }}"
- name: create connector
  add_connector:
    auth_doc: /tmp/authdoc.json
    customer: "{{ customer_name }}"
    connector_name: "{{ inventory_hostname }}"
    networks: "{{ networks | to_json }}"
  delegate_to: "{{ agilicus_sdk }}"
  register: connector
- name: debug
  debug:
    var: connector
- name: delete auth doc
  file:
    state: absent
    path: /tmp/authdoc.json
  delegate_to: "{{ agilicus_sdk }}"
